### ISSUE TITLE
No module named svg.path

### ISSUE THREAD

**Issue by loverdeveloper** [SebKuzminsky/pycam#163] opened 2020-03-14 17:39 UTC
Hi, when I start Pycam for first time I see this error:

```An unexpected exception occured: please send the text below to the developers of PyCAM. Thanks a lot!
Traceback (most recent call last):
  File "/home/mohammad/Downloads/pycam-0.6.4/pycam-0.6.4/pycam/Gui/Project.py", line 386, in gui_activity_guard_wrapper
    result = func(self, *args, **kwargs)
  File "/home/mohammad/Downloads/pycam-0.6.4/pycam-0.6.4/pycam/Gui/Project.py", line 524, in load_model_file
    detected_filetype = pycam.Importers.detect_file_type(filename)
  File "/home/mohammad/Downloads/pycam-0.6.4/pycam-0.6.4/pycam/Importers/__init__.py", line 38, in detect_file_type
    from pycam.Importers.SVGDirectImporter import import_model as import_model_from_svg
  File "/home/mohammad/Downloads/pycam-0.6.4/pycam-0.6.4/pycam/Importers/SVGDirectImporter.py", line 36, in <module>
    import svg.path
ImportError: No module named svg.path

**Comment by sumpfralle** [comment] 2020-03-15 19:23
You need to run `apt install python3-svg.path` (or similar for your distribution).

Indeed, this is a duplicate of #151.

An improved error message (mentioning the missing dependency) is already committed (cc9a12d3c2cbca3ce6ff41f8867ba0db9f401b16).

Just a release is outstanding in order to avoid people stumbling over it.

@SebKuzminsky: how about a new release for `stable/0.6`?

**Closed by sumpfralle** 2020-03-15 19:23 UTC
